<div id="product-price-range" data-bind="scope:'productpricerange'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#product-price-range": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "productpricerange": {
                        "component": "Frednguyen_ProductPriceRange/js/product-price-range"
                    }
                }
            }
        }
    }
    </script>
</div>
